services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ayacoo\Twitch\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Helper/*'

  Ayacoo\Twitch\Command\UpdateMetadataCommand:
    tags:
      - name: 'console.command'
        command: 'twitch:updateMetadata'
        description: 'Updates the Twitch metadata'
        schedulable: true
